name: Flutter Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x' # Use a recent stable Flutter version

      - name: Get dependencies
        run: flutter pub get

      - name: Build Android
        run: flutter build apk --release

      - name: Build iOS
        run: flutter build ios --no-codesign
